
server:
  port: 8080 # Default port, you can change this if needed
  servlet:
    context-path: / # Context path, set to root

spring:
  application:
    name: pen-together

  profiles:
    active: prod # Activates the production profile

  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the database schema
    show-sql: true # Show SQL queries in the log
    properties:
      hibernate:
        format_sql: true

  websocket:
    enabled: true # Enable WebSocket support
    message-broker:
      enabled: true
      broker:
        simple:
          enabled: true # Enable simple broker


# Azure-specific configurations (if deploying to Azure)
azure:
  app:
    service:
      name: ${PenTogether} # App service name (store in environment variables)
  monitor:
    diagnostics:
      enabled: true
      blob:
        enabled: true
        container-name: container-name
        sas-token: sas-token

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all management endpoints