
server:
  port: 8080 # Default port, you can change this if needed
  servlet:
    context-path: / # Context path, set to root

spring:
  application:
    name: pen-together

  profiles:
    active: prod # Activates the production profile

  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the database schema
    show-sql: true # Show SQL queries in the log
    properties:
      hibernate:
        format_sql: true

  websocket:
    message-broker:
      enabled: true
    broker:
      simple:
        enabled: true # Enable simple broker
    application-destination-prefixes: /app # Prefix for application destinations
  level:
    root: info

logging:
  level:
    root: INFO # Default logging level
    org.springframework.web: DEBUG # Debug level for Spring Web

managment:
  endpoints:
    web:
      exposure:
        include: "*"

# Azure-specific configurations (if deploying to Azure)
azure:
  application-insights:
    instrumentation-key: a44311de-dce3-4563-b800-998564890117

  signalr:
    connection-string: ${Endpoint=https://whiteboard.service.signalr.net;AccessKey=Ydl/+I+T5Q8PJDW8HN5CIQvHVX43UCjy4j1S6kS3d4U=;Version=1.0;} # SignalR connection string (store in environment variables)

    url: "wss://whiteboard.service.signalr.net"
    access-key: "Ydl/+I+T5Q8PJDW8HN5CIQvHVX43UCjy4j1S6kS3d4U="
    hub-name: "whiteboard"
  app:
    service:
      name: ${PenTogether} # App service name (store in environment variables)
  monitor:
    diagnostics:
      enabled: true
      blob:
        enabled: true
        container-name: container-name
        sas-token: sas-token


management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all management endpoints



